language: node_js
sudo: false
node_js:
- 6
script:
- npm run ci
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: qgHH2/jcM35KN9qLFLdn4UBXCy54U8kqmCy/ami1TLbYwZ+96J1zxDaSN0erygKVk18St/FO+kAnyRpzytvFSckIWpnGH7/THdnEqeIhzrXFCSJQGiyrBqdIHshLBIi78kmws5aJxo5GT2A31ch5+N0NUBhdpfLpJwtjVPsdVkx7Xjjl+nBrdjn8+p1npgIYpOen6GJEStqLNYessd6BAa8n8sKEoKdAmi7omYtiFemUgF7kVUqPCD8xqfD0LTPZOVvgMcbGYfQz3Nmenw7EWNOs6PYWlsg5H2IJMG4HJzv1Gy/6Vy8m/90S99dMaFStrSnMqyyajb+TPUR6FKYInHk13QDcCwdTFGhIDqWVPhlehEku3sOZ4uVNxKvyRS53JwhiYdz/uT6E6Fgl11t4CXr5kNc395WoMfs4nuesl/5Mz5vg/J4gnghQUcoVawXSxuetKkY+45OXyVQqFzVZAzlUFThfDT2YKE7VbevasfMuLAOF8gKrqTsiOhqI4ptsH3PW1mnnDqKzQYB/zj0iYAPIQwiZlnQVbc79RLpoJ14fOVnbZsegenPSjXN5uGNwFtt9eoFC/5wYKtGUVDHEgu3W6HJz3eBogmzJq2w2y8STnP36zSrzSQGsEDqMeWqGvEZZbrXKEzHuQgeufFsdi2MfOA1/26mUcL8C4jU/BGQ=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - secure: UoNlw7XnAnjQ+ZLQobZ5RFvnfX2HJVcKMawAZAQ6s6nw6W30mAhIH3aIcY+gpkM4541eD6b7rzfEiBLqcfr2Bjyj62/1urZ8F6AzQNXUAkc9ZQNIAoVScnqfHio4WPAuI3YnmZQ9zBJugw2wlR/mblD6zseFWdnBFkxJ2F/EiYk6oX8STwHTtSQ5q1va+Pi3vwZkOfK16PokJ5fJXuwAvacsRWyzvaq2vY4HsgvC9KdbVEDe34hL23ohFZxsqB9JPMhuRHycQwOMPYcZvFs6lDZ3dr3p92bnncgK7Z4oKNf7Oneta9WjeTQ5zif+ryRJTpd+DLZIWiLyqpgzzI0L69r/N88MuvTphCKXOWe2TShSB7r3XZcWKueuNogUYnWPxMOjOnpgXSl8r1jXGUHuw/1sS9pYx2LAkJHka9Z8AKGAgqWDAEM4oub813qe3ZuaciEN5jTOJNUxJH7J/ozqUNxdr8RDmUetCTnjP3Fk0mWsPQlVcfYRpv0HUxL5K4Kyy1D1jeA5h+PdejExybRgkodqGSCryOY2LOhKgS5EVXfnLfIWbUchfGIy+AWEdTqcrBZsvgyfVKc9aTMhcmLQGKI0bpwLurd+rm+2rorPrB8VYYdh0PR3DFmlj++8AqrGnZoIKVolIxO5Lzh7H/109hTOhGqeR1Dexatsj2JY0kU=
